task:
   path: /
   controller: App\Controller\TaskController::index

task_detail:
   path: /tarea/{id}
   controller: App\Controller\TaskController::detail

crear_view:
   path: /crear_view
   controller: App\Controller\TaskController::crear_view   

crear:
   path: /crear
   controller: App\Controller\TaskController::crear   

edit_view:
   path: /edit/{id}
   controller: App\Controller\TaskController::edit_view

editar:
   path: /editar
   controller: App\Controller\TaskController::editar

register:
   path: /registro
   controller: App\Controller\UserController::register

login:
   path: /login
   controller: App\Controller\UserController::login

logout:
   path: /logout
